### ISSUE TITLE
Segmentation fault when increase blocks' number

### ISSUE THREAD

**Issue by tangzhenyu** [Microsoft/Multiverso#141]
When I increase blocks' number,I met a Segmentation fault,following are the gdb debugging information.
Can anyone share any ideas?
Thanks you all!

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffd46403700 (LWP 37256)]
0x000000000041e83c in multiverso::Aggregator::StartThread() ()
(gdb) bt
#0  0x000000000041e83c in multiverso::Aggregator::StartThread() ()
#1  0x00007ffff7708970 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#2  0x00007ffff7965064 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#3  0x00007ffff6e7862d in clone () from /lib/x86_64-linux-gnu/libc.so.6

**Comment by WalkerWen** [comment]
I also met the same problem, do you solve it?
